# yaml-language-server: $schema=https://www.schemastore.org/github-issue-forms.json
name: 🛠️ Maintenance *
description: Maintenance for operational, infrastructure, tooling, and configration
title: "[Maint]: "
projects: ["gcco-legoteam/13"]
type: "Maintenance"
body:

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Automation / IaaC
        - Backup / Disaster Recovery
        - Compute / VM / PaaS / Containers
        - Networking / DNS / FW /etc.
        - Monitoring / Alerting / Notification
        - Storage / Data / DB
        - Billing / Reporting / Cost Management
        - Workload Provisioning
        - Other
    validations:
      required: true

  - type: dropdown
    id: csp
    attributes:
      label: Cloud Platform
      multiple: true
      options:
        - Azure
        - AWS
        - GCP
        - Entra ID
        - GitHub
        - Multi-Cloud
        - N/A

  - type: dropdown
    id: team
    attributes:
      label: Teams Involved
      multiple: true
      options:
        - EVO
        - OPS
        - External / Client
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What needs doing, and why?
      description: Outline what work needs to be done, why it needs to be done, and what's affected by this change.
    validations:
      required: true